"""empty message

Revision ID: 565cb623a64f
Revises: 
Create Date: 2020-08-16 16:12:28.261612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565cb623a64f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_fullname'), 'author', ['fullname'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    op.create_index(op.f('ix_books_type'), 'books', ['type'], unique=False)
    op.create_table('association',
    sa.Column('Books', sa.Integer(), nullable=True),
    sa.Column('Author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['Books'], ['books.id'], )
    )
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf')
    op.drop_table('association')
    op.drop_index(op.f('ix_books_type'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_author_fullname'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
